### ISSUE TITLE
Uncaught TypeError: date1.format is not a function

### ISSUE THREAD

**Issue by Romchik** [wakirin/Litepicker#132]
**Describe the bug**
https://jsfiddle.net/8hrbyw9u/
I found this demo, that showing 'onSelect' in action and using litepicker@1.0.29. All works great.
But with last version of litepicker (1.5.7) I become error:
`Uncaught TypeError: date1.format is not a function`

**To Reproduce**
https://jsfiddle.net/4n60cktm/

**Comment by Flix6x** [comment]
It seemed to work with litepicker@1.1.0 but not with litepicker@1.1.1. I think it might have stopped working with [this commit](https://github.com/wakirin/Litepicker/commit/4a6469ac655d23ea23d7c7f9dfca8d8d1ade3600) (I haven't thoroughly tested different versions).

Possible workaround: `date1.toDateString()` helped me get the format I needed.

**Comment by wakirin** [comment]
In v2 starts `DateTime` object again.

https://wakirin.github.io/Litepicker/docs/events#selected
