### ISSUE TITLE
Uncaught TypeError: date2.diff is not a function (problem 1)

### ISSUE THREAD

**Issue by kevinmu17** [wakirin/Litepicker#103]
**The bug**
I have the function used in litepicker like this: nights.value = date2.diff(date1, 'day');
This worked in version 1.0.18
I updated litepicker to the newest 1.4.6 and this suddenly stopped working.

**To Reproduce**
```
const picker = new Litepicker({
singleMode: false,
onSelect: function (date1, date2) {
nights.value = date2.diff(date1, 'day');
}
});
```
**Expected behavior**
This should give back the days in numbers.

**jsfiddle.net / codepen.io / etc**
https://codepen.io/kevinmu/pen/PoZNXzB

**Comment by scott-fisher-iii** [comment]
I don't see .diff() as a function of a date object in JavaScript.

I'd have to look, but isn't that a component of moment.js?
I believe that Moment.js was a dependency of the deprecated lightpick picker (that litepicker replaced), but not this picker.

In any case, getting the days difference between two dates can be achieved by:
<pre>// Convert milliseconds difference to days
var dayCount = Math.ceil(Math.abs(date2 - date1) / 86400000);
// 86400000 = (1000 * 60 * 60 * 24);
console.log("Difference: " + dayCount + " days");
</pre>

**Comment by wakirin** [comment]
In earlier versions, a `DateTime` object (part of Litepicker) was returned in the `onSelect` event.
In recent versions returns a `Date` object.

You can see all changes in the pull request #55

**Comment by kevinmu17** [comment]
> I don't see .diff() as a function of a date object in JavaScript.
> 
> I'd have to look, but isn't that a component of moment.js?
> I believe that Moment.js was a dependency of the deprecated lightpick picker (that litepicker replaced), but not this picker.

I thought so yes, but there is a piece of code within this current version of litepicker using the same code :)
https://github.com/wakirin/Litepicker/blob/13b64c52cbb999a282f9863a92736a1f76915b69/src/litepicker.ts#L636

This is why I thought something was broken. But your solution is working perfectly, thanks!

**Comment by scott-fisher-iii** [comment]
> > I don't see .diff() as a function of a date object in JavaScript.
> > I'd have to look, but isn't that a component of moment.js?
> > I believe that Moment.js was a dependency of the deprecated lightpick picker (that litepicker replaced), but not this picker.
> 
> I thought so yes, but there is a piece of code within this current version of litepicker using the same code :)
> https://github.com/wakirin/Litepicker/blob/13b64c52cbb999a282f9863a92736a1f76915b69/src/litepicker.ts#L636
> 
> This is why I thought something was broken. But your solution is working perfectly, thanks!

Perhaps that is a bug? Especially since @wakirin stated that Litepicker isn't using DateTime objects anymore.

**Comment by wakirin** [comment]
Not a bug.

> Especially since @wakirin stated that Litepicker isn't using DateTime objects anymore.

I didn't say that.
Inside Litepicker, the `DateTime` is still used.
